<!DOCTYPE html>
<html>
<head>
    <title>Todo List</title>
    <meta charset="UTF-8"> 
    <link rel="stylesheet" href="css/style.css">
</head>
<body> 
<script src="js/main.js"></script>
<div class="center">
<div class="flex-container">
<img src="img/todolist.png" style="width:100px;height:80px">
<div>
<h2>Todo-Liste eksempel</h2>
<span>
<a href="/">Login</a>
<a href="https://github.com/pdigre/todolist">Github</a>
</span></div>
</div>
<div class="main">
